name: Build
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          # submodules: 'true'
      - name: 安装程序依赖
        run: |
          npm i
          npm install typescript -g
      - name: 构建主程序
        run: |
          mkdir Luminide
          tsc --outDir ./Luminide/ -watch false
      - name: 复制附属文件
        run: |
          cp package.json ./Luminide/
          cp config.json ./Luminide/
      - name: 构建启动文件（Windows）
        run: |
          mkdir build-windows
          cd build-windows
          cmake ../LuminideStart/
          cmake --build . --config Release
          cd ..
      - name: 复制启动文件
        run: |
          cp ./build-windows/Release/LuminideStart.exe ./Luminide/
      - name: 上传工件
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Luminide
          path: ./Luminide/
