name: Build
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          # submodules: 'true'
      - name: 安装程序依赖
        run: |
          npm i
          npm install typescript
      - name: 构建主程序
        run: |
          mkdir Luminide
          tsc --outDir ./Luminide/ -watch false
      - name: 复制附属文件
        run: |
          cp package.json ./Luminide/
          cp config.json ./Luminide/
      - name: 构建 Linux 启动文件
        run: |
          mkdir build
          cd build
          cmake ../LuminideStart/
          make -j 4
          cd ..
      - name: 复制 Linux 启动文件
        run: cp ./build/LuminideStart ./Luminide/
      - name: 上传工件
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Luminide
          path: ./Luminide/
