name: "build-repo"
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          # submodules: 'true'
      - name: Install Requirements
        run: |
          npm i
          npm install typescript
      - name: Build Luminide
        run: |
          mkdir Luminide
          tsc --outDir ./Luminide/ -watch false
      - name: Copy Files
        run: |
          cp package.json ./Luminide/
      - name: Build Linux Startup Files
        run: |
          mkdir build
          cd build
          cmake ../LuminideStart/
          make -j 4
      - name: Copy Linux Startup Files
        run: cp ./build/LuminideStart ./Luminide/
      - name: Upload Luminide
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Luminide
          path: ./Luminide/
