name: 'Release'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - Auto-Release

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Requirements    
        run: |
          npm i
          npm install typescript
      - name: Build TMBot    
        run: |
         mkdir build
         tsc --outDir ./build/ -watch false
      - name: Copy Files
        run: |
          cp start.bat ./build/
          cp start.sh ./build/
          cp package.json ./build/
      - name: Pack Release
        id: pack
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          cd build
          7z a TMBot-Release.zip -r
          ls ../
          echo -------------
          ls 
      - name: Read Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Read Description
        id: description
        uses: juliangruber/read-file-action@v1
        with:
          path: ./description.txt
      - name: Upload TMBot
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TMBot
          path: TMBot-Release.zip
    #  - name: Release
    #   uses: softprops/action-gh-release@v1
    #     if: startsWith(github.ref, 'refs/tags/')
    #     with:
    #       body_path: ${{ github.workspace }}-CHANGELOG.txt
    #       token: ${{ secrets.RELEASE_TOKEN }}
    #       files: |
    #         Release.txt
    #         LICENSE
    #     env:
    #       GITHUB_REPOSITORY: TMBotDev/TMBot

            




