name: "Release"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  push:
    branches:
      - Auto-Release

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Requirements
        run: |
          npm i
          npm install typescript
      - name: Build Luminide
        run: |
          mkdir Luminide
          tsc --outDir ./Luminide/ -watch false
      - name: Copy Files
        run: |
          cp LuminideStart.exe ./Luminide/
          cp package.json ./Luminide/
      - name: Build Linux Startup Files
        run: |
          mkdir build
          cd build
          cmake ../LuminideStart/
          make -j 4
      - name: Pack Release
        id: pack
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          cd Luminide
          7z a Luminide-Release.zip -r
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Upload Luminide
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Luminide
          path: ./Luminide/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/Release-Description.md
          tag_name: v${{steps.version.outputs.prop}}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            ./Luminide/Luminide-Release.zip
        env:
          GITHUB_REPOSITORY: Peckot-Studios/Luminide
