name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: 安装程序依赖
        run: |
          npm i
          npm install typescript -g
      - name: 构建主程序
        run: |
          mkdir Luminide
          tsc --outDir ./Luminide/ -watch false
      - name: 复制附属文件
        run: |
          cp package.json ./Luminide/
          cp config.json ./Luminide/
      - name: 构建启动程序（Linux）
        run: |
          mkdir build-linux
          cd build-linux
          cmake ../LuminideStart/
          make -j 4
          cd ..
      # - name: 构建启动程序（Windows）
      #   run: |
      #     mkdir build-windows
      #     cd build-windows
      #     cmake --build . --config Release
      #     make -j 4
      #     cd ..
      - name: 复制启动程序
        run: |
          cp ./build-linux/LuminideStart ./Luminide/
          cp ./LuminideStart.exe ./Luminide/
      #     cp ./build-windows/Release/LuminideStart.exe ./Luminide/
      - name: 打包文件
        id: pack
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          cd Luminide
          7z a Luminide-Release.zip -r
      - name: 获取版本号
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package.json
          prop_path: version
      - name: 上传工件
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Luminide
          path: ./Luminide/
      - name: 发布程序
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/.github/Release-Description.md
          tag_name: v${{ steps.version.outputs.prop }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            ./Luminide/Luminide-Release.zip
        env:
          GITHUB_REPOSITORY: Peckot-Studios/Luminide
